### ISSUE TITLE
Workers don't seem to use spot instances

### ISSUE THREAD

**Issue by nbrys** [EngineerBetter/control-tower#33] opened 2019-07-12 12:16 UTC
We have started our concourse deployment using:

`(assume-aws-role ops-operations)$ ./control-tower-darwin-amd64 deploy --region eu-west-1 --iaas aws --workers 2 --spot=true --worker-type m5 --worker-size large --web-size medium --add-tag Project=Concourse --domain concoursemaster-production.joske.com--github-auth-client-id id1 --github-auth-client-secret id2 --allow-ips 8.8.8.8 concourse-id`

When looking in the AWS console, we don't see spot instances for our worker nodes and we don't see anything related to spot instances on our AWS bill.

**Comment by crsimmons** [comment] 2019-07-31 10:15
There was a bug which should be resolved in https://github.com/EngineerBetter/control-tower/releases/tag/0.7.1

It's worth noting that we prioritise deploying something over deploying only spot instances. This means if you attempt to deploy to a region where your requested vm type is under high demand for spots, the deployment may default to on-demand instances.

You can check spot demand in the [Spot Instance Advisor](https://aws.amazon.com/ec2/spot/instance-advisor/).

**Comment by nbrys** [comment] 2019-07-31 12:15
What price do you set for m5.large instances? I upgraded our current deploy with the above command again with control tower 0.7.1 and still no spot instances

**Comment by crsimmons** [comment] 2019-07-31 13:08
We set the bid price to 0.13 which is defined [in the cloud config](https://github.com/EngineerBetter/control-tower/blob/master/resource/assets/aws/cloud-config.yml#L73)

**Comment by nbrys** [comment] 2019-07-31 13:10
The current price in eu-west-1 is 0.036 and I can request spot instances using the AWS Console. But concourse is still deployed without spot instances.

**Comment by crsimmons** [comment] 2019-07-31 13:45
I just tried deploying with `control-tower deploy --iaas aws --region eu-west-1 --workers 2 --spot=true --worker-type m5 --worker-size large concourse-id` using 0.7.1 and I'm seeing both workers as having Lifecycle `spot`.

**Comment by nbrys** [comment] 2019-07-31 13:48
Could you create a deployment without spot instances, and change the spot boolean afterward? Should I see this change in the terraform part of the deploy?

**Comment by crsimmons** [comment] 2019-09-04 11:22
I did some more testing and was unable to replicate this issue.

First deploy:
`ct deploy --iaas aws --region eu-west-1 --workers 2 --spot=false --worker-type m5 --worker-size large cs-spots2`

Second deploy:
`ct deploy --iaas aws --region eu-west-1 --workers 2 --spot=true --worker-type m5 --worker-size large cs-spots2`

It deployed first without spots then successfully swapped over to using spots.

I'm going to close this issue as it has been inactive for a while and I cannot reproduce.

**Closed by crsimmons** 2019-09-04 11:22 UTC
