### ISSUE TITLE
SHA256 mismatch for 0.13.12 package in Brew

### ISSUE THREAD

**Issue by hiepunity3d** [EngineerBetter/control-tower#85] opened 2020-12-17 21:28 UTC
**Problem**

I tried to install the latest version of `control-tower` but couldn't since the SHA256 of packages were mismatched. Here is the log provided by `brew`:
```sh
$ brew install engineerbetter/tap/control-tower
Updating Homebrew...
==> Installing control-tower from engineerbetter/tap
==> Downloading https://github.com/EngineerBetter/control-tower/releases/download/0.13.12/control-tower-da
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/173088799/8d4abc00-33
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 893b42792c76be15fef42c4286a81e83f1edcd14a16f02c18c335fd09e9a0c6d
  Actual: d5f217da39f8d4760e7a4481f404f70e415923cc231e9e8c98c9db082ac80fe6
  File: ~/Library/Caches/Homebrew/downloads/6a2b68bb060d1fa5e5a0dbc1156339f23dd7abba748f9920560e43057ca96089--control-tower-darwin-amd64
To retry an incomplete download, remove the file above.
```

**Comment by DanielJonesEB** [comment] 2020-12-18 06:26
Thanks for lettings us know, @hiepunity3d. I can confirm that I can reproduce the issue.

**Comment by DanielJonesEB** [comment] 2020-12-18 06:37
This should be fixed now @hiepunity3d. Looks like we've got a problem in our pipeline that is failing to bump the minor revision when making automated releases.

**Closed by DanielJonesEB** 2020-12-18 06:37 UTC
